### ISSUE TITLE
Download CSV/etc Directly from Website

### ISSUE THREAD

**Issue by jon49** [matthewrwilton/csv-citibank-statement#5]
Although this is a pretty cool project it looks like you can download the CSV.

On the main page you can click on `Accounts` > `your account` > `Scroll to bottom under Transactions` > Change time period to time period you desire > On the right side you will see an export option > choose `CSV` or `Text` or `QFX` or ... This is for <citi.com>. So, I'm not sure if this would work for you or not.

**Comment by jon49** [comment]
lol, just noticed this was written 4/5 years ago! :-)

**Comment by matthewrwilton** [comment]
Thanks for letting me know @jon49! That option might have been around back then as well, and I might just have missed it.

I do have another project that I still use which takes that data and sticks it into a Google Sheet (https://github.com/matthewrwilton/citibank-statement-to-sheets) and occasionally I have to make an adjustment when something in the PDF changes. Next time that happens I think I'll rewrite it to use the CSV download.
